import json,pathlib,hashlib
p=pathlib.Path(__file__).resolve().parent
read=lambda n:json.loads((p/n).read_text())
b=read('baseline.json');a=read('patched.json');f=read('baseline.frozen.json')
progress=[json.loads(x) for x in (p/'patched.progress.jsonl').read_text().splitlines()]
rr=[x for x in progress if x.get('event')=='rrt_checkpoint'];starts=[x for x in progress if x.get('event')=='connection_started'];ends=[x for x in progress if x.get('event')=='connection_finished']
entry=next(x for x in progress if x.get('event')=='stage_enter' and x.get('entry')=='_connect_pose')
source=read('source_01a9282.json');root=p.parent/'source-01a9282'
unchanged=all(hashlib.sha256((root/n).read_bytes()).hexdigest()==h for n,h in source['files'].items())
assert unchanged
summary=dict(review_baseline='20c7a375a263c825182427b30ac53c6a4215b8d6',source_commit=source['commit'],baseline_execution_source='0bfd708489219b8635b836ab307c186faa7f03e6',baseline_code_identical_to_review_baseline=True,archive_sha256=source['archive_sha256'],archive_files_verified=len(source['files']),archive_files_unchanged=unchanged,target='carton_l07_c04',start_q=f['start_q'],preplace_virtual=f['preplace_virtual'],placement=f['placement'],input_sha256=hashlib.sha256((p/'baseline.frozen.json').read_bytes()).hexdigest(),attachment=f['attachment'],tracker=f['tracker'],extraction_nodes=len(f['extraction']),prefix_scope='PREVIOUS_APPROACH_REUSED_EXTRACTION_RECONSTRUCTED_AND_RECHECKED_NOT_PHYSICAL_EXECUTION',validation_context=read('account_patched.json')['context_id'],account_baseline=read('account_baseline.json'),account_patched=read('account_patched.json'),baseline_connection_seconds=b['evidence']['elapsed_seconds'],baseline_connection_state_checks=b['evidence']['expensive_states'],baseline_total_seconds=b['elapsed_seconds'],baseline_rrt_expanded=b['evidence']['rrt_expanded'],patched_status=a['status'],patched_failure=a['failure'],patched_total_seconds=a['elapsed_seconds'],patched_connection_seconds=a['elapsed_seconds']-entry['elapsed_s'],patched_connection_state_checks=a['statistics']['state_validations']-entry['statistics']['state_validations'],patched_total_state_checks=a['statistics']['state_validations'],rrt_connections_started=starts,rrt_connections_finished=ends,last_rrt_checkpoint=rr[-1] if rr else None,rrt_extension_count_semantics='LOWER_BOUND_AT_LAST_FLUSHED_CHECKPOINT_WHEN_INTERRUPTED',completed_rrt_iterations=None if not ends else sum(x['iterations'] for x in ends),local_shared_after=a['local_shared_after'],source_unchanged=a['source_unchanged'],inputs_unchanged=a['inputs_unchanged'],cpu=dict(passed=346,skipped=22,failed=0,seconds=24.55,run=read('cpu_run_01a9282.json')),full_new_cycle=False,execution_export=False,independent_preflight=False,bundle_readback=False,isaac_executed=False,full_cycle_not_started_reason='NO_VALID_LOADED_CONNECTION' if a['status']!='VALID' else 'PENDING_CONDITIONAL_FULL_ATTEMPT',setup_note='One premature archive extraction caused an import SyntaxError before planning. Log retained; complete archive and all 269 files verified before the actual patched fragment run.')
(p/'summary.json').write_text(json.dumps(summary,indent=2))
print(json.dumps({k:summary[k] for k in ['patched_status','patched_failure','patched_connection_seconds','patched_connection_state_checks','last_rrt_checkpoint','source_unchanged','inputs_unchanged']},indent=2))
